language: python
python:
  - '3.7'
dist: xenial
sudo: true
before_install:
  - pip install poetry
install:
  - poetry install -n
script:
  - poetry run flake8 .
  - poetry run mypy .
before_deploy:
  - poetry build -n
deploy:
  provider: script
  script: poetry publish -n -u "${PYPI_USERNAME}" -p "${PYPI_PASSWORD}"
  skip_cleanup: true
  on:
    tags: true
